function logAuditOperation(name,rowsBefore,rowsAfter,cellsAffected){const timestamp=new Date().toISOString();auditOperations.push({operationName:name,rowsBefore,rowsAfter,cellsAffected,timestamp});}
function displayAuditLog(){const container=document.getElementById('auditLogDisplay');if(!container)return;container.innerHTML='';if(auditOperations.length===0){container.innerHTML='<p>no operations logged</p>';return;}auditOperations.forEach(op=>{const div=document.createElement('div');div.style.marginBottom='10px';div.innerHTML=`<strong>${op.operationName}</strong><br/>rows before: ${op.rowsBefore}, after: ${op.rowsAfter}<br/>timestamp: ${op.timestamp}`;container.appendChild(div);});const summary=document.getElementById('cleaningSummaryLine');if(summary){const rowsRemoved=originalCSV.trim().split('\n').length-cleanedCSV.trim().split('\n').length;summary.textContent=`cleaned: ${rowsRemoved} rows removed, ${cleanedCSV.trim().split('\n').length-1} rows remaining`;}}
function beginProfiling(){document.getElementById('welcomeSection').classList.add('hidden');document.getElementById('structuredSection').style.display='block';document.getElementById('uploadSection').style.display='none';document.getElementById('cleaningSection').style.display='block';}
function getColumnCount(){return uploadCSV.trim().split('\n')[0].split(',').length;}
function downloadAsCSV(){triggerDownload(cleanedCSV,'cleaned_data.csv','text/csv');}
function downloadAsJSON(){const json=JSON.stringify(cleanedCSV,null,2);triggerDownload(json,'cleaned_data.json','application/json');}
function downloadAsTSV(){const tsv=cleanedCSV.replace(/,/g,'\t');triggerDownload(tsv,'cleaned_data.tsv','text/tab-separated-values');}
function triggerDownload(content,filename,type){const blob=new Blob([content],{type});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=filename;a.click();URL.revokeObjectURL(url);}
function downloadAuditLogJSON(){const json=JSON.stringify(auditOperations,null,2);triggerDownload(json,'audit_log.json','application/json');}function downloadAuditReport(){const report=`AUDIT REPORT\n${'='.repeat(80)}\nGenerated: ${new Date().toISOString()}\n\n`;let detail='OPERATIONS\n'+'-'.repeat(80)+'\n';for(let i=0;i<auditOperations.length;i++){const op=auditOperations[i];detail+=`${i+1}. ${op.operationName}\n   Timestamp: ${op.timestamp}\n   Rows before: ${op.rowsBefore}\n   Rows after: ${op.rowsAfter}\n   Cells affected: ${op.cellsAffected}\n\n`;}const summary=`SUMMARY\n${'-'.repeat(80)}\nTotal operations: ${auditOperations.length}\nInitial rows: ${auditOperations.length>0?auditOperations[0].rowsBefore:0}\nFinal rows: ${auditOperations.length>0?auditOperations[auditOperations.length-1].rowsAfter:0}\n`;triggerDownload(report+detail+summary,'audit_report.txt','text/plain');}
